=== WinPlay02/mc-versions/schemas/version.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://skyrising.github.io/mc-versions/schemas/version.json",
    "$defs": {
        "version": {
            "description": "A version in the Omniarchive format",
            "type": "string",
            "pattern": "^(((server-)?([abc]|inf?-|rd-|af-)?[0-9]+[.0-9]*)|[0-9]{2}w[0-9]{2}[a-z~])a?([_-][0-9a-z]+)*$"
        },
        "semver": {
            "description": "A version number in SemVer format (see https://semver.org/ for the specification)",
            "type": "string",
            "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
        },
        "releaseType": {
            "description": "A release type (e.g. release, snapshot, etc.)",
            "type": "string",
            "pattern": "^[a-z_]+$",
            "examples": ["release", "snapshot", "old_alpha", "old_beta"]
        },
        "sha1": {
            "description": "The SHA-1 hash of a file",
            "type": "string",
            "pattern": "^[0-9a-f]{40}$"
        },
        "downloadInfo": {
            "type": "object",
            "properties": {
                "sha1": {"$ref": "#/$defs/sha1"},
                "size": {"type": "integer", "minimum": 0},
                "url": {"type": "string", "format": "uri"}
            },
            "additionalProperties": false
        },
        "protocolVersion": {
            "type": "object",
            "properties": {
                "type": {"enum": ["classic", "modern", "netty", "netty-snapshot"]},
                "version": {"type": "integer", "minimum": 0}
            },
            "required": ["type", "version"],
            "additionalProperties": false
        },
        "worldFormat": {
            "type": "object",
            "properties": {
                "format": {"enum": ["alpha", "region", "anvil"]},
                "version": {"type": "integer"}
            },
            "required": ["format"],
            "additionalProperties": false
        },
        "manifestInfo": {
            "type": "object",
            "properties": {
                "assetHash": {"$ref": "#/$defs/sha1"},
                "assetIndex": {"type": "string"},
                "downloads": {"$ref": "#/$defs/sha1"},
                "downloadsId": {"type": "integer", "minimum": 1},
                "hash": {"$ref": "#/$defs/sha1"},
                "time": {"type": "string", "format": "date-time"},
                "type": {"$ref": "#/$defs/releaseType"},
                "url": {"type": "string", "format": "uri-reference"}
            }
        }
    },
    "type": "object",
    "properties": {
        "id": {"$ref": "#/$defs/version"},
        "client": {
            "type": "boolean",
            "description": "Whether `downloads` includes a client"
        },
        "server": {
            "type": "boolean",
            "description": "Whether `downloads` includes a server"
        },
        "sharedMappings": {
            "type": "boolean",
            "description": "Whether the obfuscation mappings for client and server are the same"
        },
        "downloads": {
            "patternProperties": {
                "^[a-z_]*$": {"$ref": "#/$defs/downloadInfo"}
            },
            "additionalProperties": false
        },
        "libraries": {
            "type": "array",
            "items": {"type": "string"}
        },
        "manifests": {
            "type": "array",
            "items": {"$ref": "#/$defs/manifestInfo"}
        },
        "normalizedVersion": {"$ref": "#/$defs/semver"},
        "previous": {"type": "array", "items": {"$ref": "#/$defs/version"}},
        "next": {"type": "array", "items": {"$ref": "#/$defs/version"}},
        "releaseTarget": {"$ref": "#/$defs/semver"},
        "releaseTime": {"type": "string", "format": "date-time"},
        "protocol": {
            "oneOf": [{
                "type": "object",
                "properties": {
                    "type": {"enum": ["classic", "modern", "netty", "netty-snapshot"]},
                    "version": {"type": "integer", "minimum": 0}
                },
                "required": ["type", "version"],
                "additionalProperties": false
            }, {
                "type": "null"
            }]
        },
        "world": {"$ref": "#/$defs/worldFormat"}
    },
    "required": ["id", "client", "server", "downloads", "normalizedVersion", "previous", "next", "releaseTarget", "releaseTime", "protocol", "world", "libraries"]
}

=== WinPlay02/mc-versions/version/20w20b.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "ff70a84c9cdc99a866c4b06410ec46f541dcf988",
      "size": 17234567,
      "url": "https://launcher.mojang.com/v1/objects/ff70a84c9cdc99a866c4b06410ec46f541dcf988/client.jar"
    },
    "client_mappings": {
      "sha1": "6f20bbe4218c895f621aeb60e9874674891a21b5",
      "size": 5425299,
      "url": "https://launcher.mojang.com/v1/objects/6f20bbe4218c895f621aeb60e9874674891a21b5/client.txt"
    },
    "server": {
      "sha1": "0393774fb1f9db8288a56dbbcf45022b71f7939f",
      "size": 37554531,
      "url": "https://launcher.mojang.com/v1/objects/0393774fb1f9db8288a56dbbcf45022b71f7939f/server.jar"
    },
    "server_mappings": {
      "sha1": "940a087b56105319bd32960a8241c68c55cf9aea",
      "size": 4163637,
      "url": "https://launcher.mojang.com/v1/objects/940a087b56105319bd32960a8241c68c55cf9aea/server.txt"
    }
  },
  "id": "20w20b",
  "libraries": [
    "com.google.code.gson:gson:2.8.0",
    "com.google.guava:guava:21.0",
    "com.ibm.icu:icu4j:66.1",
    "com.mojang:authlib:1.6.25",
    "com.mojang:brigadier:1.0.17",
    "com.mojang:datafixerupper:2.0.24",
    "com.mojang:javabridge:1.0.22",
    "com.mojang:patchy:1.3.9",
    "com.mojang:text2speech:1.11.3",
    "commons-codec:commons-codec:1.10",
    "commons-io:commons-io:2.5",
    "commons-logging:commons-logging:1.1.3",
    "io.netty:netty-all:4.1.25.Final",
    "it.unimi.dsi:fastutil:8.2.1",
    "net.java.dev.jna:jna:4.4.0",
    "net.java.dev.jna:platform:3.4.0",
    "net.java.jinput:jinput:2.0.5",
    "net.java.jutils:jutils:1.0.0",
    "net.sf.jopt-simple:jopt-simple:5.0.3",
    "org.apache.commons:commons-compress:1.8.1",
    "org.apache.commons:commons-lang3:3.5",
    "org.apache.httpcomponents:httpclient:4.3.3",
    "org.apache.httpcomponents:httpcore:4.3.2",
    "org.apache.logging.log4j:log4j-api:2.8.1",
    "org.apache.logging.log4j:log4j-core:2.8.1",
    "org.lwjgl:lwjgl-glfw:3.2.2",
    "org.lwjgl:lwjgl-jemalloc:3.2.2",
    "org.lwjgl:lwjgl-openal:3.2.2",
    "org.lwjgl:lwjgl-opengl:3.2.2",
    "org.lwjgl:lwjgl-stb:3.2.2",
    "org.lwjgl:lwjgl-tinyfd:3.2.2",
    "org.lwjgl:lwjgl:3.2.2",
    "oshi-project:oshi-core:1.1"
  ],
  "manifests": [
    {
      "assetHash": "28680197f74e5e1d55054f6a63509c8298d428f9",
      "assetIndex": "1.16",
      "downloads": "9c7264175371f889e9fd1acdb91d5fcc1d7628e7",
      "downloadsId": 1,
      "hash": "5480903121430c43adb7a416275a16bdf4f892ad",
      "lastModified": "2022-02-25T13:39:20+00:00",
      "time": "2020-05-14T08:16:26+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/5/4/80903121430c43adb7a416275a16bdf4f892ad/20w20b.json"
    },
    {
      "assetHash": "738b17ea266089b5e384791eb5a2cf1fafe109b6",
      "assetIndex": "1.16",
      "downloads": "9c7264175371f889e9fd1acdb91d5fcc1d7628e7",
      "downloadsId": 1,
      "hash": "63010786652e87c08a451081596506bd2e8f4db8",
      "lastModified": "2021-12-15T15:52:22+00:00",
      "time": "2020-05-14T08:16:26+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/6/3/010786652e87c08a451081596506bd2e8f4db8/20w20b.json"
    },
    {
      "assetHash": "738b17ea266089b5e384791eb5a2cf1fafe109b6",
      "assetIndex": "1.16",
      "downloads": "9c7264175371f889e9fd1acdb91d5fcc1d7628e7",
      "downloadsId": 1,
      "hash": "8fc732503c1271083b3c4023cfa0c05c6cf62180",
      "lastModified": "2021-12-10T02:58:42+00:00",
      "time": "2020-05-14T08:16:26+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/8/f/c732503c1271083b3c4023cfa0c05c6cf62180/20w20b.json"
    },
    {
      "assetHash": "738b17ea266089b5e384791eb5a2cf1fafe109b6",
      "assetIndex": "1.16",
      "downloads": "9c7264175371f889e9fd1acdb91d5fcc1d7628e7",
      "downloadsId": 1,
      "hash": "f77ca0d2199f33b88d71ec1f87734e3bec674616",
      "lastModified": "2021-11-30T09:49:06+00:00",
      "time": "2020-05-14T08:16:26+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/f/7/7ca0d2199f33b88d71ec1f87734e3bec674616/20w20b.json"
    },
    {
      "assetHash": "ad75fb46ff5c89aa5f9c90e12481e963854f9a6e",
      "assetIndex": "1.16",
      "downloads": "9c7264175371f889e9fd1acdb91d5fcc1d7628e7",
      "downloadsId": 1,
      "hash": "562a6ab86f1668c091b27b633be6bee018f60d31",
      "lastModified": "2021-07-07T13:56:18+00:00",
      "time": "2020-05-14T08:16:26+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/5/6/2a6ab86f1668c091b27b633be6bee018f60d31/20w20b.json"
    },
    {
      "assetHash": "ad75fb46ff5c89aa5f9c90e12481e963854f9a6e",
      "assetIndex": "1.16",
      "downloads": "9c7264175371f889e9fd1acdb91d5fcc1d7628e7",
      "downloadsId": 1,
      "hash": "c37c6bb50811868714edfd36adfaf6fcbd3fe86c",
      "lastModified": "2021-06-29T15:20:37+00:00",
      "time": "2020-05-14T08:16:26+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/c/3/7c6bb50811868714edfd36adfaf6fcbd3fe86c/20w20b.json"
    },
    {
      "assetHash": "3a5d110a6ab102c7083bae4296d2de4b8fcf92eb",
      "assetIndex": "1.16",
      "downloads": "9c7264175371f889e9fd1acdb91d5fcc1d7628e7",
      "downloadsId": 1,
      "hash": "4d234e2814357344cd6c895abfdd8c88ab8031d2",
      "lastModified": "2021-01-13T14:12:35+00:00",
      "time": "2020-05-14T08:16:26+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/4/d/234e2814357344cd6c895abfdd8c88ab8031d2/20w20b.json"
    },
    {
      "assetHash": "f8e11ca03b475dd655755b945334c7a0ac2c3b43",
      "assetIndex": "1.16",
      "downloads": "9c7264175371f889e9fd1acdb91d5fcc1d7628e7",
      "downloadsId": 1,
      "hash": "ed56963a8838431b77f653eb0e3e4875b195e29b",
      "lastModified": "2020-12-02T16:57:25+00:00",
      "time": "2020-05-14T08:16:26+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/e/d/56963a8838431b77f653eb0e3e4875b195e29b/20w20b.json"
    },
    {
      "assetHash": "6aeb80664ca8c3c1e114f9ee428bb0bd7d29b1ab",
      "assetIndex": "1.16",
      "downloads": "9c7264175371f889e9fd1acdb91d5fcc1d7628e7",
      "downloadsId": 1,
      "hash": "76258d97b9a45d708e3891166dcc7f5667c9eedf",
      "lastModified": "2020-11-02T16:33:52+00:00",
      "time": "2020-05-14T08:16:26+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/7/6/258d97b9a45d708e3891166dcc7f5667c9eedf/20w20b.json"
    }
  ],
  "next": [
    "20w21a"
  ],
  "normalizedVersion": "1.16.0-alpha.20.20.b",
  "previous": [
    "20w20a"
  ],
  "protocol": {
    "type": "netty",
    "version": 717
  },
  "releaseTarget": "1.16",
  "releaseTime": "2020-05-14T08:16:26+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 2537
  }
}

=== WinPlay02/mc-versions/version/16w39c.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "417fe811581f045d4f5de0381b08cd7dc3744c41",
      "size": 9250850,
      "url": "https://launcher.mojang.com/v1/objects/417fe811581f045d4f5de0381b08cd7dc3744c41/client.jar"
    },
    "server": {
      "sha1": "df13c6cbf5fc735896b22f56b1f8940dd11a3b5f",
      "size": 9695321,
      "url": "https://launcher.mojang.com/v1/objects/df13c6cbf5fc735896b22f56b1f8940dd11a3b5f/server.jar"
    }
  },
  "id": "16w39c",
  "libraries": [
    "com.google.code.gson:gson:2.2.4",
    "com.google.guava:guava:17.0",
    "com.ibm.icu:icu4j-core-mojang:51.2",
    "com.mojang:authlib:1.5.24",
    "com.mojang:netty:1.8.8",
    "com.mojang:realms:1.9.3",
    "com.paulscode:codecjorbis:20101023",
    "com.paulscode:codecwav:20101023",
    "com.paulscode:libraryjavasound:20101123",
    "com.paulscode:librarylwjglopenal:20100824",
    "com.paulscode:soundsystem:20120107",
    "commons-codec:commons-codec:1.9",
    "commons-io:commons-io:2.4",
    "commons-logging:commons-logging:1.1.3",
    "io.netty:netty-all:4.0.23.Final",
    "it.unimi.dsi:fastutil:7.0.12_mojang",
    "net.java.dev.jna:jna:3.4.0",
    "net.java.dev.jna:platform:3.4.0",
    "net.java.jinput:jinput-platform:2.0.5",
    "net.java.jinput:jinput:2.0.5",
    "net.java.jutils:jutils:1.0.0",
    "net.sf.jopt-simple:jopt-simple:4.6",
    "org.apache.commons:commons-compress:1.8.1",
    "org.apache.commons:commons-lang3:3.3.2",
    "org.apache.httpcomponents:httpclient:4.3.3",
    "org.apache.httpcomponents:httpcore:4.3.2",
    "org.apache.logging.log4j:log4j-api:2.0-beta9",
    "org.apache.logging.log4j:log4j-core:2.0-beta9",
    "org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209",
    "org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209",
    "org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209",
    "oshi-project:oshi-core:1.1"
  ],
  "manifests": [
    {
      "assetHash": "4fa7f939c7e9902e6c674ad1d00358f8c08d7b8e",
      "assetIndex": "1.11",
      "downloads": "761fd3555dd8fc736da39c713e08d7906a18819b",
      "downloadsId": 1,
      "hash": "cb6d954c591717c457863f84b004246778a51ce7",
      "lastModified": "2021-12-15T15:57:27+00:00",
      "time": "2016-09-30T14:11:48+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/c/b/6d954c591717c457863f84b004246778a51ce7/16w39c.json"
    },
    {
      "assetHash": "4fa7f939c7e9902e6c674ad1d00358f8c08d7b8e",
      "assetIndex": "1.11",
      "downloads": "761fd3555dd8fc736da39c713e08d7906a18819b",
      "downloadsId": 1,
      "hash": "a4d4887ea35bc35e35037a4a74a389e70f3f4f5b",
      "lastModified": "2021-07-07T14:00:58+00:00",
      "time": "2016-09-30T14:11:48+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/a/4/d4887ea35bc35e35037a4a74a389e70f3f4f5b/16w39c.json"
    },
    {
      "assetHash": "4fa7f939c7e9902e6c674ad1d00358f8c08d7b8e",
      "assetIndex": "1.11",
      "downloads": "761fd3555dd8fc736da39c713e08d7906a18819b",
      "downloadsId": 1,
      "hash": "b6072818f323b5e9ea51f1e501880a9e88025144",
      "lastModified": "2018-08-29T13:00:00+00:00",
      "time": "2016-09-30T14:11:48+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/b/6/072818f323b5e9ea51f1e501880a9e88025144/16w39c.json"
    }
  ],
  "next": [
    "16w40a"
  ],
  "normalizedVersion": "1.11.0-alpha.16.39.c",
  "previous": [
    "16w39b"
  ],
  "protocol": {
    "type": "netty",
    "version": 309
  },
  "releaseTarget": "1.11",
  "releaseTime": "2016-09-30T14:11:48+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 812
  }
}

=== WinPlay02/mc-versions/version/14w30b.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "3a0d41e74a18e2c26498a918724ff39d62af329c",
      "size": 7590320,
      "url": "https://launcher.mojang.com/v1/objects/3a0d41e74a18e2c26498a918724ff39d62af329c/client.jar"
    },
    "server": {
      "sha1": "ee24a6e63b007b9ec97a591afe1a29a6bbbfe143",
      "size": 10328935,
      "url": "https://launcher.mojang.com/v1/objects/ee24a6e63b007b9ec97a591afe1a29a6bbbfe143/server.jar"
    },
    "windows_server": {
      "sha1": "fb80a59b1159f2a57edc0f837846253f89fdb379",
      "size": 10723175,
      "url": "https://launcher.mojang.com/v1/objects/fb80a59b1159f2a57edc0f837846253f89fdb379/windows_server.exe"
    }
  },
  "id": "14w30b",
  "libraries": [
    "com.google.code.gson:gson:2.2.4",
    "com.google.guava:guava:17.0",
    "com.ibm.icu:icu4j-core-mojang:51.2",
    "com.mojang:authlib:1.5.16",
    "com.mojang:netty:1.8.8",
    "com.mojang:realms:1.5",
    "com.paulscode:codecjorbis:20101023",
    "com.paulscode:codecwav:20101023",
    "com.paulscode:libraryjavasound:20101123",
    "com.paulscode:librarylwjglopenal:20100824",
    "com.paulscode:soundsystem:20120107",
    "commons-codec:commons-codec:1.9",
    "commons-io:commons-io:2.4",
    "commons-logging:commons-logging:1.1.3",
    "io.netty:netty-all:4.0.15.Final",
    "java3d:vecmath:1.5.2",
    "net.java.jinput:jinput-platform:2.0.5",
    "net.java.jinput:jinput:2.0.5",
    "net.java.jutils:jutils:1.0.0",
    "net.sf.jopt-simple:jopt-simple:4.6",
    "net.sf.trove4j:trove4j:3.0.3",
    "org.apache.commons:commons-compress:1.8.1",
    "org.apache.commons:commons-lang3:3.3.2",
    "org.apache.httpcomponents:httpclient:4.3.3",
    "org.apache.httpcomponents:httpcore:4.3.2",
    "org.apache.logging.log4j:log4j-api:2.0-beta9",
    "org.apache.logging.log4j:log4j-core:2.0-beta9",
    "org.lwjgl.lwjgl:lwjgl-platform:2.9.1",
    "org.lwjgl.lwjgl:lwjgl:2.9.1",
    "org.lwjgl.lwjgl:lwjgl_util:2.9.1",
    "tv.twitch:twitch-platform:6.5",
    "tv.twitch:twitch:6.5"
  ],
  "manifests": [
    {
      "assetHash": "32ff354a3be1c4dd83027111e6d79ee4d701d2c0",
      "assetIndex": "14w25a",
      "downloads": "4b2b131b070e094bc5e63e09d925cdcf4e264210",
      "downloadsId": 1,
      "hash": "6cb8e867a0ce10649fe22a22f7ecaad42fd33383",
      "lastModified": "2021-12-15T16:00:22+00:00",
      "time": "2014-07-23T15:03:03+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/6/c/b8e867a0ce10649fe22a22f7ecaad42fd33383/14w30b.json"
    },
    {
      "assetHash": "32ff354a3be1c4dd83027111e6d79ee4d701d2c0",
      "assetIndex": "14w25a",
      "downloads": "4b2b131b070e094bc5e63e09d925cdcf4e264210",
      "downloadsId": 1,
      "hash": "447b5f4d11bb57230a8f33aa5b288b964a9daa2b",
      "lastModified": "2021-07-07T14:03:39+00:00",
      "time": "2014-07-23T15:03:03+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/4/4/7b5f4d11bb57230a8f33aa5b288b964a9daa2b/14w30b.json"
    },
    {
      "assetHash": "32ff354a3be1c4dd83027111e6d79ee4d701d2c0",
      "assetIndex": "14w25a",
      "downloads": "4b2b131b070e094bc5e63e09d925cdcf4e264210",
      "downloadsId": 1,
      "hash": "57bcfcbdd1b88e8bf9acdad43e866ee56be0a73d",
      "lastModified": "2018-08-29T13:01:49+00:00",
      "time": "2014-07-23T15:03:03+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/5/7/bcfcbdd1b88e8bf9acdad43e866ee56be0a73d/14w30b.json"
    }
  ],
  "next": [
    "14w30c"
  ],
  "normalizedVersion": "1.8.0-alpha.14.30.b",
  "previous": [
    "14w30a"
  ],
  "protocol": {
    "type": "netty",
    "version": 30
  },
  "releaseTarget": "1.8",
  "releaseTime": "2014-07-23T15:03:03+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil"
  }
}

=== WinPlay02/mc-versions/version/16w50a-1438.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "925650c3ed9e1e79dd3f846a49a9de3a7f8e700c",
      "size": 9194941,
      "url": "https://launcher.mojang.com/v1/objects/925650c3ed9e1e79dd3f846a49a9de3a7f8e700c/client.jar"
    },
    "server": {
      "sha1": "d4d30a5433846d205974ace4cf34c9b294e0833f",
      "size": 9720347,
      "url": "https://launcher.mojang.com/v1/objects/d4d30a5433846d205974ace4cf34c9b294e0833f/server.jar"
    }
  },
  "id": "16w50a-1438",
  "libraries": [
    "com.google.code.gson:gson:2.2.4",
    "com.google.guava:guava:17.0",
    "com.ibm.icu:icu4j-core-mojang:51.2",
    "com.mojang:authlib:1.5.24",
    "com.mojang:netty:1.8.8",
    "com.mojang:realms:1.10.1",
    "com.paulscode:codecjorbis:20101023",
    "com.paulscode:codecwav:20101023",
    "com.paulscode:libraryjavasound:20101123",
    "com.paulscode:librarylwjglopenal:20100824",
    "com.paulscode:soundsystem:20120107",
    "commons-codec:commons-codec:1.9",
    "commons-io:commons-io:2.4",
    "commons-logging:commons-logging:1.1.3",
    "io.netty:netty-all:4.0.23.Final",
    "it.unimi.dsi:fastutil:7.0.12_mojang",
    "net.java.dev.jna:jna:3.4.0",
    "net.java.dev.jna:platform:3.4.0",
    "net.java.jinput:jinput-platform:2.0.5",
    "net.java.jinput:jinput:2.0.5",
    "net.java.jutils:jutils:1.0.0",
    "net.sf.jopt-simple:jopt-simple:4.6",
    "org.apache.commons:commons-compress:1.8.1",
    "org.apache.commons:commons-lang3:3.3.2",
    "org.apache.httpcomponents:httpclient:4.3.3",
    "org.apache.httpcomponents:httpcore:4.3.2",
    "org.apache.logging.log4j:log4j-api:2.0-beta9",
    "org.apache.logging.log4j:log4j-core:2.0-beta9",
    "org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209",
    "org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209",
    "org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209",
    "oshi-project:oshi-core:1.1"
  ],
  "manifests": [
    {
      "assetHash": "4fa7f939c7e9902e6c674ad1d00358f8c08d7b8e",
      "assetIndex": "1.11",
      "downloads": "da79a4bc0d63f1057e9b68602e488deb608c80c2",
      "downloadsId": 1,
      "hash": "5829dc5e58d3d7d5d55417aa5290f12bd0481d5d",
      "lastModified": "2021-12-15T15:57:17+00:00",
      "time": "2016-12-15T14:38:52+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/5/8/29dc5e58d3d7d5d55417aa5290f12bd0481d5d/16w50a.json"
    },
    {
      "assetHash": "4fa7f939c7e9902e6c674ad1d00358f8c08d7b8e",
      "assetIndex": "1.11",
      "downloads": "da79a4bc0d63f1057e9b68602e488deb608c80c2",
      "downloadsId": 1,
      "hash": "c1bef2a0ec1759336e9e4c63071be42b00f4f5a1",
      "lastModified": "2021-07-07T14:00:49+00:00",
      "time": "2016-12-15T14:38:52+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/c/1/bef2a0ec1759336e9e4c63071be42b00f4f5a1/16w50a.json"
    },
    {
      "assetHash": "4fa7f939c7e9902e6c674ad1d00358f8c08d7b8e",
      "assetIndex": "1.11",
      "downloads": "da79a4bc0d63f1057e9b68602e488deb608c80c2",
      "downloadsId": 1,
      "hash": "78cdc6813ea2b31011e3cbe96c91bcf5c58af725",
      "lastModified": "2018-08-29T12:59:54+00:00",
      "time": "2016-12-15T14:38:52+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/7/8/cdc6813ea2b31011e3cbe96c91bcf5c58af725/16w50a.json"
    }
  ],
  "next": [
    "1.11.1"
  ],
  "normalizedVersion": "1.11.1-alpha.16.50.a+1438",
  "previous": [
    "1.11"
  ],
  "protocol": {
    "type": "netty",
    "version": 316
  },
  "releaseTarget": "1.11.1",
  "releaseTime": "2016-12-15T14:38:52+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 920
  }
}

=== WinPlay02/mc-versions/version/19w03a.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "7280ee42cce1c0371c96c95c22170d3aea7068bb",
      "size": 17842319,
      "url": "https://launcher.mojang.com/v1/objects/7280ee42cce1c0371c96c95c22170d3aea7068bb/client.jar"
    },
    "server": {
      "sha1": "1e80738a5360887bc93a46bdffb07699a45bf5a1",
      "size": 35200780,
      "url": "https://launcher.mojang.com/v1/objects/1e80738a5360887bc93a46bdffb07699a45bf5a1/server.jar"
    }
  },
  "id": "19w03a",
  "libraries": [
    "com.google.code.gson:gson:2.8.0",
    "com.google.guava:guava:21.0",
    "com.ibm.icu:icu4j-core-mojang:51.2",
    "com.mojang:authlib:1.5.25",
    "com.mojang:brigadier:1.0.14",
    "com.mojang:datafixerupper:2.0.23",
    "com.mojang:javabridge:1.0.22",
    "com.mojang:patchy:1.3.9",
    "com.mojang:realms:1.14.1",
    "com.mojang:text2speech:1.10.3",
    "com.paulscode:codecjorbis:20101023",
    "com.paulscode:codecwav:20101023",
    "com.paulscode:libraryjavasound:20101123",
    "com.paulscode:soundsystem:20120107",
    "commons-codec:commons-codec:1.10",
    "commons-io:commons-io:2.5",
    "commons-logging:commons-logging:1.1.3",
    "io.netty:netty-all:4.1.25.Final",
    "it.unimi.dsi:fastutil:8.2.1",
    "net.java.dev.jna:jna:4.4.0",
    "net.java.dev.jna:platform:3.4.0",
    "net.java.jinput:jinput:2.0.5",
    "net.java.jutils:jutils:1.0.0",
    "net.sf.jopt-simple:jopt-simple:5.0.3",
    "org.apache.commons:commons-compress:1.8.1",
    "org.apache.commons:commons-lang3:3.5",
    "org.apache.httpcomponents:httpclient:4.3.3",
    "org.apache.httpcomponents:httpcore:4.3.2",
    "org.apache.logging.log4j:log4j-api:2.8.1",
    "org.apache.logging.log4j:log4j-core:2.8.1",
    "org.lwjgl:lwjgl-glfw:3.1.6",
    "org.lwjgl:lwjgl-jemalloc:3.1.6",
    "org.lwjgl:lwjgl-openal:3.1.6",
    "org.lwjgl:lwjgl-opengl:3.1.6",
    "org.lwjgl:lwjgl-stb:3.1.6",
    "org.lwjgl:lwjgl:3.1.6",
    "oshi-project:oshi-core:1.1"
  ],
  "manifests": [
    {
      "assetHash": "d6c94fad4f7a03a8e46083c023926515fc0e551e",
      "assetIndex": "1.14",
      "downloads": "db2c80c4d931ad74cba6ddf854138c538a5f551a",
      "downloadsId": 1,
      "hash": "ffb4179a65b7b0a73ff310c81cf8fa4860116433",
      "lastModified": "2021-12-15T15:54:53+00:00",
      "time": "2019-01-16T16:45:02+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/f/f/b4179a65b7b0a73ff310c81cf8fa4860116433/19w03a.json"
    },
    {
      "assetHash": "d6c94fad4f7a03a8e46083c023926515fc0e551e",
      "assetIndex": "1.14",
      "downloads": "db2c80c4d931ad74cba6ddf854138c538a5f551a",
      "downloadsId": 1,
      "hash": "18d121b2f0c016a29876928893778696d0190e76",
      "lastModified": "2021-12-10T03:01:00+00:00",
      "time": "2019-01-16T16:45:02+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/1/8/d121b2f0c016a29876928893778696d0190e76/19w03a.json"
    },
    {
      "assetHash": "d6c94fad4f7a03a8e46083c023926515fc0e551e",
      "assetIndex": "1.14",
      "downloads": "db2c80c4d931ad74cba6ddf854138c538a5f551a",
      "downloadsId": 1,
      "hash": "8b82852f830c148644176c4e0c639bbab50b97ff",
      "lastModified": "2021-07-07T13:58:36+00:00",
      "time": "2019-01-16T16:45:02+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/8/b/82852f830c148644176c4e0c639bbab50b97ff/19w03a.json"
    },
    {
      "assetHash": "d6c94fad4f7a03a8e46083c023926515fc0e551e",
      "assetIndex": "1.14",
      "downloads": "db2c80c4d931ad74cba6ddf854138c538a5f551a",
      "downloadsId": 1,
      "hash": "4240d571c4259253aa504f261a24cba05ba2824a",
      "lastModified": "2019-08-22T12:49:10+00:00",
      "time": "2019-01-16T16:45:02+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/4/2/40d571c4259253aa504f261a24cba05ba2824a/19w03a.json"
    }
  ],
  "next": [
    "19w03b"
  ],
  "normalizedVersion": "1.14.0-alpha.19.3.a",
  "previous": [
    "19w02a"
  ],
  "protocol": {
    "type": "netty",
    "version": 453
  },
  "releaseTarget": "1.14",
  "releaseTime": "2019-01-16T16:45:02+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 1922
  }
}
