=== WinPlay02/mc-versions/schemas/version.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://skyrising.github.io/mc-versions/schemas/version.json",
    "$defs": {
        "version": {
            "description": "A version in the Omniarchive format",
            "type": "string",
            "pattern": "^(((server-)?([abc]|inf?-|rd-|af-)?[0-9]+[.0-9]*)|[0-9]{2}w[0-9]{2}[a-z~])a?([_-][0-9a-z]+)*$"
        },
        "semver": {
            "description": "A version number in SemVer format (see https://semver.org/ for the specification)",
            "type": "string",
            "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
        },
        "releaseType": {
            "description": "A release type (e.g. release, snapshot, etc.)",
            "type": "string",
            "pattern": "^[a-z_]+$",
            "examples": ["release", "snapshot", "old_alpha", "old_beta"]
        },
        "sha1": {
            "description": "The SHA-1 hash of a file",
            "type": "string",
            "pattern": "^[0-9a-f]{40}$"
        },
        "downloadInfo": {
            "type": "object",
            "properties": {
                "sha1": {"$ref": "#/$defs/sha1"},
                "size": {"type": "integer", "minimum": 0},
                "url": {"type": "string", "format": "uri"}
            },
            "additionalProperties": false
        },
        "protocolVersion": {
            "type": "object",
            "properties": {
                "type": {"enum": ["classic", "modern", "netty", "netty-snapshot"]},
                "version": {"type": "integer", "minimum": 0}
            },
            "required": ["type", "version"],
            "additionalProperties": false
        },
        "worldFormat": {
            "type": "object",
            "properties": {
                "format": {"enum": ["alpha", "region", "anvil"]},
                "version": {"type": "integer"}
            },
            "required": ["format"],
            "additionalProperties": false
        },
        "manifestInfo": {
            "type": "object",
            "properties": {
                "assetHash": {"$ref": "#/$defs/sha1"},
                "assetIndex": {"type": "string"},
                "downloads": {"$ref": "#/$defs/sha1"},
                "downloadsId": {"type": "integer", "minimum": 1},
                "hash": {"$ref": "#/$defs/sha1"},
                "time": {"type": "string", "format": "date-time"},
                "type": {"$ref": "#/$defs/releaseType"},
                "url": {"type": "string", "format": "uri-reference"}
            }
        }
    },
    "type": "object",
    "properties": {
        "id": {"$ref": "#/$defs/version"},
        "client": {
            "type": "boolean",
            "description": "Whether `downloads` includes a client"
        },
        "server": {
            "type": "boolean",
            "description": "Whether `downloads` includes a server"
        },
        "sharedMappings": {
            "type": "boolean",
            "description": "Whether the obfuscation mappings for client and server are the same"
        },
        "downloads": {
            "patternProperties": {
                "^[a-z_]*$": {"$ref": "#/$defs/downloadInfo"}
            },
            "additionalProperties": false
        },
        "libraries": {
            "type": "array",
            "items": {"type": "string"}
        },
        "manifests": {
            "type": "array",
            "items": {"$ref": "#/$defs/manifestInfo"}
        },
        "normalizedVersion": {"$ref": "#/$defs/semver"},
        "previous": {"type": "array", "items": {"$ref": "#/$defs/version"}},
        "next": {"type": "array", "items": {"$ref": "#/$defs/version"}},
        "releaseTarget": {"$ref": "#/$defs/semver"},
        "releaseTime": {"type": "string", "format": "date-time"},
        "protocol": {
            "oneOf": [{
                "type": "object",
                "properties": {
                    "type": {"enum": ["classic", "modern", "netty", "netty-snapshot"]},
                    "version": {"type": "integer", "minimum": 0}
                },
                "required": ["type", "version"],
                "additionalProperties": false
            }, {
                "type": "null"
            }]
        },
        "world": {"$ref": "#/$defs/worldFormat"}
    },
    "required": ["id", "client", "server", "downloads", "normalizedVersion", "previous", "next", "releaseTarget", "releaseTime", "protocol", "world", "libraries"]
}

=== WinPlay02/mc-versions/version/1.14-pre3.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "12f85e0b940f3649c9ecb5a3201811f56992e5c0",
      "size": 18747283,
      "url": "https://launcher.mojang.com/v1/objects/12f85e0b940f3649c9ecb5a3201811f56992e5c0/client.jar"
    },
    "server": {
      "sha1": "6b747e1338e1aa058146032a659cf654c446552d",
      "size": 35900398,
      "url": "https://launcher.mojang.com/v1/objects/6b747e1338e1aa058146032a659cf654c446552d/server.jar"
    }
  },
  "id": "1.14-pre3",
  "libraries": [
    "com.google.code.gson:gson:2.8.0",
    "com.google.guava:guava:21.0",
    "com.ibm.icu:icu4j-core-mojang:51.2",
    "com.mojang:authlib:1.5.25",
    "com.mojang:brigadier:1.0.17",
    "com.mojang:datafixerupper:2.0.24",
    "com.mojang:javabridge:1.0.22",
    "com.mojang:patchy:1.3.9",
    "com.mojang:realms:1.14.8",
    "com.mojang:text2speech:1.11.3",
    "commons-codec:commons-codec:1.10",
    "commons-io:commons-io:2.5",
    "commons-logging:commons-logging:1.1.3",
    "io.netty:netty-all:4.1.25.Final",
    "it.unimi.dsi:fastutil:8.2.1",
    "net.java.dev.jna:jna:4.4.0",
    "net.java.dev.jna:platform:3.4.0",
    "net.java.jinput:jinput:2.0.5",
    "net.java.jutils:jutils:1.0.0",
    "net.sf.jopt-simple:jopt-simple:5.0.3",
    "org.apache.commons:commons-compress:1.8.1",
    "org.apache.commons:commons-lang3:3.5",
    "org.apache.httpcomponents:httpclient:4.3.3",
    "org.apache.httpcomponents:httpcore:4.3.2",
    "org.apache.logging.log4j:log4j-api:2.8.1",
    "org.apache.logging.log4j:log4j-core:2.8.1",
    "org.lwjgl:lwjgl-glfw:3.2.1",
    "org.lwjgl:lwjgl-jemalloc:3.2.1",
    "org.lwjgl:lwjgl-openal:3.2.1",
    "org.lwjgl:lwjgl-opengl:3.2.1",
    "org.lwjgl:lwjgl-stb:3.2.1",
    "org.lwjgl:lwjgl:3.2.1",
    "oshi-project:oshi-core:1.1"
  ],
  "manifests": [
    {
      "assetHash": "d6c94fad4f7a03a8e46083c023926515fc0e551e",
      "assetIndex": "1.14",
      "downloads": "53999aa6514192dccafd648cc08a2638f984bc96",
      "downloadsId": 1,
      "hash": "afc93c4946c93e90f0c98034bbfccaa8f41b2891",
      "lastModified": "2021-12-15T15:54:21+00:00",
      "time": "2019-04-16T13:57:10+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/a/f/c93c4946c93e90f0c98034bbfccaa8f41b2891/1.14%20Pre-Release%203.json"
    },
    {
      "assetHash": "d6c94fad4f7a03a8e46083c023926515fc0e551e",
      "assetIndex": "1.14",
      "downloads": "53999aa6514192dccafd648cc08a2638f984bc96",
      "downloadsId": 1,
      "hash": "12a0e962034414654519d8cf6f4455708b5492e4",
      "lastModified": "2021-12-10T03:00:31+00:00",
      "time": "2019-04-16T13:57:10+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/1/2/a0e962034414654519d8cf6f4455708b5492e4/1.14%20Pre-Release%203.json"
    },
    {
      "assetHash": "d6c94fad4f7a03a8e46083c023926515fc0e551e",
      "assetIndex": "1.14",
      "downloads": "53999aa6514192dccafd648cc08a2638f984bc96",
      "downloadsId": 1,
      "hash": "1f8c8d9cd34dc7e0bb1c079e3001db31ea249eed",
      "lastModified": "2021-07-07T13:58:07+00:00",
      "time": "2019-04-16T13:57:10+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/1/f/8c8d9cd34dc7e0bb1c079e3001db31ea249eed/1.14%20Pre-Release%203.json"
    },
    {
      "assetHash": "d6c94fad4f7a03a8e46083c023926515fc0e551e",
      "assetIndex": "1.14",
      "downloads": "53999aa6514192dccafd648cc08a2638f984bc96",
      "downloadsId": 1,
      "hash": "a276012e0ab0d6b54d38e7a402bc373413d65b4d",
      "lastModified": "2019-08-22T12:48:49+00:00",
      "time": "2019-04-16T13:57:10+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/a/2/76012e0ab0d6b54d38e7a402bc373413d65b4d/1.14_Pre-Release_3.json"
    }
  ],
  "next": [
    "1.14-pre4"
  ],
  "normalizedVersion": "1.14.0-pre.3",
  "previous": [
    "1.14-pre2"
  ],
  "protocol": {
    "type": "netty",
    "version": 474
  },
  "releaseTarget": "1.14",
  "releaseTime": "2019-04-16T13:57:10+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 1949
  }
}

=== WinPlay02/mc-versions/version/13w25a.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "b397e5bcf74858ce8f527c62c973087a0ea518a8",
      "size": 4703294,
      "url": "https://launcher.mojang.com/v1/objects/b397e5bcf74858ce8f527c62c973087a0ea518a8/client.jar"
    },
    "server": {
      "sha1": "e1c2e7376fe489c5eba744b010993c402ab3f3f2",
      "size": 7183331,
      "url": "https://launcher.mojang.com/v1/objects/e1c2e7376fe489c5eba744b010993c402ab3f3f2/server.jar"
    },
    "windows_server": {
      "sha1": "7ad6c310e5837343279377a6010d33a8e82d62d3",
      "size": 7579107,
      "url": "https://launcher.mojang.com/v1/objects/7ad6c310e5837343279377a6010d33a8e82d62d3/windows_server.exe"
    }
  },
  "id": "13w25a",
  "libraries": [
    "argo:argo:2.25_fixed",
    "com.google.code.gson:gson:2.2.2",
    "com.google.guava:guava:14.0",
    "com.paulscode:codecjorbis:20101023",
    "com.paulscode:codecwav:20101023",
    "com.paulscode:libraryjavasound:20101123",
    "com.paulscode:librarylwjglopenal:20100824",
    "com.paulscode:soundsystem:20120107",
    "commons-io:commons-io:2.4",
    "net.java.jinput:jinput-platform:2.0.5",
    "net.java.jinput:jinput:2.0.5",
    "net.java.jutils:jutils:1.0.0",
    "net.sf.jopt-simple:jopt-simple:4.5",
    "org.apache.commons:commons-lang3:3.1",
    "org.bouncycastle:bcprov-jdk15on:1.47",
    "org.lwjgl.lwjgl:lwjgl-platform:2.9.0",
    "org.lwjgl.lwjgl:lwjgl:2.9.0",
    "org.lwjgl.lwjgl:lwjgl_util:2.9.0"
  ],
  "manifests": [
    {
      "assetHash": "770572e819335b6c0a053f8378ad88eda189fc14",
      "assetIndex": "legacy",
      "downloads": "b98395be60513ea9883649d0e37ff4c7c71461f2",
      "downloadsId": 1,
      "hash": "ff06bab6eeb35131a9ae436d149ef914dea484e7",
      "lastModified": "2018-08-29T13:02:43+00:00",
      "time": "2013-06-17T14:08:06+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/f/f/06bab6eeb35131a9ae436d149ef914dea484e7/13w25a.json"
    }
  ],
  "next": [
    "13w25b"
  ],
  "normalizedVersion": "1.6.0-alpha.13.25.a",
  "previous": [
    "13w24b"
  ],
  "protocol": {
    "type": "modern",
    "version": 71
  },
  "releaseTarget": "1.6",
  "releaseTime": "2013-06-17T14:08:06+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil"
  }
}

=== WinPlay02/mc-versions/version/12w22a.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "3631a714cb465d39f5cb5c18aa23abf38031b359",
      "size": 4542344,
      "url": "https://files.betacraft.uk/launcher/assets/versions/1.3/12w22a.jar"
    },
    "server": {
      "sha1": "110a02fc92768a66ca32f73376e17d62518070ba",
      "size": 1766213,
      "url": "https://files.betacraft.uk/server-archive/release/1.3/prerelease/12w22a.jar"
    },
    "windows_server": {
      "sha1": "d6c4330b25544b543107b1e10e189ea44feb63d1",
      "size": 1947461,
      "url": "https://files.betacraft.uk/server-archive/release/1.3/prerelease/12w22a.exe"
    }
  },
  "id": "12w22a",
  "libraries": [
    "net.java.jinput:jinput-platform:2.0.5",
    "net.java.jinput:jinput:2.0.5",
    "net.java.jutils:jutils:1.0.0",
    "net.minecraft:launchwrapper:1.5",
    "net.sf.jopt-simple:jopt-simple:4.5",
    "org.lwjgl.lwjgl:lwjgl-platform:2.9.0",
    "org.lwjgl.lwjgl:lwjgl:2.9.0",
    "org.lwjgl.lwjgl:lwjgl_util:2.9.0",
    "org.ow2.asm:asm-all:4.1"
  ],
  "manifests": [
    {
      "assetHash": "4759bad2824e419da9db32861fcdc3a274336532",
      "assetIndex": "pre-1.6",
      "downloads": "3d12fac19d57c246b84f8c0345808cdf6c607df3",
      "downloadsId": 1,
      "hash": "ce3de9c4b1e678e86f44527666a2921d8e05bd73",
      "time": "2012-05-31T09:20:18+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/c/e/3de9c4b1e678e86f44527666a2921d8e05bd73/12w22a.json"
    }
  ],
  "next": [
    "12w23a"
  ],
  "normalizedVersion": "1.3.0-alpha.12.22.a",
  "previous": [
    "12w21b"
  ],
  "protocol": {
    "type": "modern",
    "version": 34
  },
  "releaseTarget": "1.3",
  "releaseTime": "2012-05-31T09:20:18+00:00",
  "server": true,
  "sharedMappings": false,
  "world": {
    "format": "anvil"
  }
}

=== WinPlay02/mc-versions/version/13w25c.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "f0f3a912f7a929cc21b6340c5e552ed28f90fa94",
      "size": 4709948,
      "url": "https://launcher.mojang.com/v1/objects/f0f3a912f7a929cc21b6340c5e552ed28f90fa94/client.jar"
    },
    "server": {
      "sha1": "0f21dbd39728a50843d1b20cf832f26aaada353d",
      "size": 7183727,
      "url": "https://launcher.mojang.com/v1/objects/0f21dbd39728a50843d1b20cf832f26aaada353d/server.jar"
    },
    "windows_server": {
      "sha1": "5a48f00f68abd9278144eb1930d49ae9a3ba10fd",
      "size": 7579503,
      "url": "https://launcher.mojang.com/v1/objects/5a48f00f68abd9278144eb1930d49ae9a3ba10fd/windows_server.exe"
    }
  },
  "id": "13w25c",
  "libraries": [
    "argo:argo:2.25_fixed",
    "com.google.code.gson:gson:2.2.2",
    "com.google.guava:guava:14.0",
    "com.paulscode:codecjorbis:20101023",
    "com.paulscode:codecwav:20101023",
    "com.paulscode:libraryjavasound:20101123",
    "com.paulscode:librarylwjglopenal:20100824",
    "com.paulscode:soundsystem:20120107",
    "commons-io:commons-io:2.4",
    "net.java.jinput:jinput-platform:2.0.5",
    "net.java.jinput:jinput:2.0.5",
    "net.java.jutils:jutils:1.0.0",
    "net.sf.jopt-simple:jopt-simple:4.5",
    "org.apache.commons:commons-lang3:3.1",
    "org.bouncycastle:bcprov-jdk15on:1.47",
    "org.lwjgl.lwjgl:lwjgl-platform:2.9.0",
    "org.lwjgl.lwjgl:lwjgl:2.9.0",
    "org.lwjgl.lwjgl:lwjgl_util:2.9.0"
  ],
  "manifests": [
    {
      "assetHash": "770572e819335b6c0a053f8378ad88eda189fc14",
      "assetIndex": "legacy",
      "downloads": "2e37aa56544acaa005ca09a06f6d2026289002c2",
      "downloadsId": 1,
      "hash": "45432877e0be49c9a94d7d7ce4c48d46be10c1a1",
      "lastModified": "2018-08-29T13:02:42+00:00",
      "time": "2013-06-20T15:23:37+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/4/5/432877e0be49c9a94d7d7ce4c48d46be10c1a1/13w25c.json"
    }
  ],
  "next": [
    "13w26a"
  ],
  "normalizedVersion": "1.6.0-alpha.13.25.c",
  "previous": [
    "13w25b"
  ],
  "protocol": {
    "type": "modern",
    "version": 71
  },
  "releaseTarget": "1.6",
  "releaseTime": "2013-06-20T15:23:37+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil"
  }
}

=== WinPlay02/mc-versions/version/13w09c.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "1367ef1410c2ce7ac0f1c58727aa4883c8677469",
      "size": 5533426,
      "url": "https://assets.minecraft.net/13w09c/minecraft.jar"
    },
    "server": {
      "sha1": "02b4297ed54620128a5e6da3eb4de35399e97583",
      "size": 2336343,
      "url": "https://assets.minecraft.net/13w09c/minecraft_server.jar"
    },
    "windows_server": {
      "sha1": "694b934fdcd0d0f16c2bc6186709f42e9ca61f69",
      "size": 2517591,
      "url": "https://assets.minecraft.net/13w09c/Minecraft_Server.exe"
    }
  },
  "id": "13w09c",
  "libraries": [
    "net.java.jinput:jinput-platform:2.0.5",
    "net.java.jinput:jinput:2.0.5",
    "net.java.jutils:jutils:1.0.0",
    "net.minecraft:launchwrapper:1.5",
    "net.sf.jopt-simple:jopt-simple:4.5",
    "org.lwjgl.lwjgl:lwjgl-platform:2.9.0",
    "org.lwjgl.lwjgl:lwjgl:2.9.0",
    "org.lwjgl.lwjgl:lwjgl_util:2.9.0",
    "org.ow2.asm:asm-all:4.1"
  ],
  "manifests": [
    {
      "assetHash": "4759bad2824e419da9db32861fcdc3a274336532",
      "assetIndex": "pre-1.6",
      "downloads": "28232e5db248f418355b0f4531f912ee59c03624",
      "downloadsId": 1,
      "hash": "e685068275acd8566eb48dec7b5b8b37d7a8e099",
      "time": "2013-03-01T14:58:38+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/e/6/85068275acd8566eb48dec7b5b8b37d7a8e099/13w09c.json"
    }
  ],
  "next": [
    "13w10a"
  ],
  "normalizedVersion": "1.5.0-alpha.13.9.c",
  "previous": [
    "13w09b"
  ],
  "protocol": {
    "type": "modern",
    "version": 60
  },
  "releaseTarget": "1.5",
  "releaseTime": "2013-03-01T14:58:38+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil"
  }
}

=== WinPlay02/mc-versions/version/16w33a.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "e565f6a8dacc85b81faaf17e4a13125b2ad5c335",
      "size": 8889021,
      "url": "https://launcher.mojang.com/v1/objects/e565f6a8dacc85b81faaf17e4a13125b2ad5c335/client.jar"
    },
    "server": {
      "sha1": "dfdda3e5ba769ba0634ad43ca1124a401d6addca",
      "size": 9482198,
      "url": "https://launcher.mojang.com/v1/objects/dfdda3e5ba769ba0634ad43ca1124a401d6addca/server.jar"
    }
  },
  "id": "16w33a",
  "libraries": [
    "com.google.code.gson:gson:2.2.4",
    "com.google.guava:guava:17.0",
    "com.ibm.icu:icu4j-core-mojang:51.2",
    "com.mojang:authlib:1.5.22",
    "com.mojang:netty:1.8.8",
    "com.mojang:realms:1.9.3",
    "com.paulscode:codecjorbis:20101023",
    "com.paulscode:codecwav:20101023",
    "com.paulscode:libraryjavasound:20101123",
    "com.paulscode:librarylwjglopenal:20100824",
    "com.paulscode:soundsystem:20120107",
    "commons-codec:commons-codec:1.9",
    "commons-io:commons-io:2.4",
    "commons-logging:commons-logging:1.1.3",
    "io.netty:netty-all:4.0.23.Final",
    "it.unimi.dsi:fastutil:7.0.12_mojang",
    "net.java.dev.jna:jna:3.4.0",
    "net.java.dev.jna:platform:3.4.0",
    "net.java.jinput:jinput-platform:2.0.5",
    "net.java.jinput:jinput:2.0.5",
    "net.java.jutils:jutils:1.0.0",
    "net.sf.jopt-simple:jopt-simple:4.6",
    "org.apache.commons:commons-compress:1.8.1",
    "org.apache.commons:commons-lang3:3.3.2",
    "org.apache.httpcomponents:httpclient:4.3.3",
    "org.apache.httpcomponents:httpcore:4.3.2",
    "org.apache.logging.log4j:log4j-api:2.0-beta9",
    "org.apache.logging.log4j:log4j-core:2.0-beta9",
    "org.lwjgl.lwjgl:lwjgl-platform:2.9.4-nightly-20150209",
    "org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209",
    "org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209",
    "oshi-project:oshi-core:1.1"
  ],
  "manifests": [
    {
      "assetHash": "4fa7f939c7e9902e6c674ad1d00358f8c08d7b8e",
      "assetIndex": "1.11",
      "downloads": "1f1eacd6de1c2f9d1fecebddcf42c3254e403252",
      "downloadsId": 1,
      "hash": "af926a6f83f05a29f4412bf3b47fa1da868002d5",
      "lastModified": "2021-12-15T15:57:35+00:00",
      "time": "2016-08-17T12:48:57+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/a/f/926a6f83f05a29f4412bf3b47fa1da868002d5/16w33a.json"
    },
    {
      "assetHash": "4fa7f939c7e9902e6c674ad1d00358f8c08d7b8e",
      "assetIndex": "1.11",
      "downloads": "1f1eacd6de1c2f9d1fecebddcf42c3254e403252",
      "downloadsId": 1,
      "hash": "2337af653ba055ec8ee23b89bd107e37de848a66",
      "lastModified": "2021-07-07T14:01:05+00:00",
      "time": "2016-08-17T12:48:57+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/2/3/37af653ba055ec8ee23b89bd107e37de848a66/16w33a.json"
    },
    {
      "assetHash": "4fa7f939c7e9902e6c674ad1d00358f8c08d7b8e",
      "assetIndex": "1.11",
      "downloads": "1f1eacd6de1c2f9d1fecebddcf42c3254e403252",
      "downloadsId": 1,
      "hash": "4a721222564bb3b9635f04efd12734622b1eb8ae",
      "lastModified": "2018-08-29T13:00:05+00:00",
      "time": "2016-08-17T12:48:57+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/4/a/721222564bb3b9635f04efd12734622b1eb8ae/16w33a.json"
    }
  ],
  "next": [
    "16w35a"
  ],
  "normalizedVersion": "1.11.0-alpha.16.33.a",
  "previous": [
    "16w32b"
  ],
  "protocol": {
    "type": "netty",
    "version": 303
  },
  "releaseTarget": "1.11",
  "releaseTime": "2016-08-17T12:48:57+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 802
  }
}

=== WinPlay02/mc-versions/version/12w08a.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "db2fcfdd23526b0f381ef2f3f2fd049d36227230",
      "size": 3981486,
      "url": "https://assets.minecraft.net/12w08a/minecraft.jar"
    },
    "server": {
      "sha1": "d0583dfd8466ea1368010d2a964e6ab0c0aaa0d1",
      "size": 1342476,
      "url": "https://assets.minecraft.net/12w08a/minecraft_server.jar"
    }
  },
  "id": "12w08a",
  "libraries": [
    "net.java.jinput:jinput-platform:2.0.5",
    "net.java.jinput:jinput:2.0.5",
    "net.java.jutils:jutils:1.0.0",
    "net.minecraft:launchwrapper:1.5",
    "net.sf.jopt-simple:jopt-simple:4.5",
    "org.lwjgl.lwjgl:lwjgl-platform:2.9.0",
    "org.lwjgl.lwjgl:lwjgl:2.9.0",
    "org.lwjgl.lwjgl:lwjgl_util:2.9.0",
    "org.ow2.asm:asm-all:4.1"
  ],
  "manifests": [
    {
      "assetHash": "4759bad2824e419da9db32861fcdc3a274336532",
      "assetIndex": "pre-1.6",
      "downloads": "49630142e1e5d9d627539048d7968d0b5e79cfad",
      "downloadsId": 1,
      "hash": "df49ac55f89ccb5b94c432ec4372c3384f091928",
      "time": "2012-02-23T15:12:46+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/d/f/49ac55f89ccb5b94c432ec4372c3384f091928/12w08a.json"
    }
  ],
  "next": [
    "1.2"
  ],
  "normalizedVersion": "1.2.0-alpha.12.8.a",
  "previous": [
    "12w07b"
  ],
  "protocol": {
    "type": "modern",
    "version": 28
  },
  "releaseTarget": "1.2",
  "releaseTime": "2012-02-23T15:12:46+00:00",
  "server": true,
  "sharedMappings": false,
  "world": {
    "format": "anvil"
  }
}

=== WinPlay02/mc-versions/version/1.13-pre9.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "4dedcb718a3382496d19d13cfe5dc070528a15cd",
      "size": 16016754,
      "url": "https://launcher.mojang.com/v1/objects/4dedcb718a3382496d19d13cfe5dc070528a15cd/client.jar"
    },
    "server": {
      "sha1": "ee66f5cb1247f4340734a151db4f940bbe04f833",
      "size": 32640589,
      "url": "https://launcher.mojang.com/v1/objects/ee66f5cb1247f4340734a151db4f940bbe04f833/server.jar"
    }
  },
  "id": "1.13-pre9",
  "libraries": [
    "com.google.code.gson:gson:2.8.0",
    "com.google.guava:guava:21.0",
    "com.ibm.icu:icu4j-core-mojang:51.2",
    "com.mojang:authlib:1.5.25",
    "com.mojang:brigadier:0.1.27",
    "com.mojang:datafixerupper:1.0.16",
    "com.mojang:patchy:1.3.9",
    "com.mojang:text2speech:1.10.3",
    "com.paulscode:codecjorbis:20101023",
    "com.paulscode:codecwav:20101023",
    "com.paulscode:libraryjavasound:20101123",
    "com.paulscode:soundsystem:20120107",
    "commons-codec:commons-codec:1.10",
    "commons-io:commons-io:2.5",
    "commons-logging:commons-logging:1.1.3",
    "io.netty:netty-all:4.1.25.Final",
    "it.unimi.dsi:fastutil:7.1.0",
    "net.java.dev.jna:jna:4.4.0",
    "net.java.dev.jna:platform:3.4.0",
    "net.java.jinput:jinput:2.0.5",
    "net.java.jutils:jutils:1.0.0",
    "net.sf.jopt-simple:jopt-simple:5.0.3",
    "org.apache.commons:commons-compress:1.8.1",
    "org.apache.commons:commons-lang3:3.5",
    "org.apache.httpcomponents:httpclient:4.3.3",
    "org.apache.httpcomponents:httpcore:4.3.2",
    "org.apache.logging.log4j:log4j-api:2.8.1",
    "org.apache.logging.log4j:log4j-core:2.8.1",
    "org.lwjgl:lwjgl-glfw:3.1.6",
    "org.lwjgl:lwjgl-jemalloc:3.1.6",
    "org.lwjgl:lwjgl-openal:3.1.6",
    "org.lwjgl:lwjgl-opengl:3.1.6",
    "org.lwjgl:lwjgl-stb:3.1.6",
    "org.lwjgl:lwjgl:3.1.6",
    "oshi-project:oshi-core:1.1"
  ],
  "manifests": [
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "4e078b2a0d4f3adc0a76343952284df03e203461",
      "downloadsId": 1,
      "hash": "a345b4dd358f307c6c3654781fa6525930ec4b04",
      "lastModified": "2021-12-15T15:55:32+00:00",
      "time": "2018-07-16T14:17:42+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/a/3/45b4dd358f307c6c3654781fa6525930ec4b04/1.13-pre9.json"
    },
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "4e078b2a0d4f3adc0a76343952284df03e203461",
      "downloadsId": 1,
      "hash": "46ee1ac597369b9ee177d80135d58073c7a0e2ea",
      "lastModified": "2021-12-10T03:01:37+00:00",
      "time": "2018-07-16T14:17:42+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/4/6/ee1ac597369b9ee177d80135d58073c7a0e2ea/1.13-pre9.json"
    },
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "4e078b2a0d4f3adc0a76343952284df03e203461",
      "downloadsId": 1,
      "hash": "ed83da33e735ab2b523946de9f2b0b9f2db134af",
      "lastModified": "2021-07-07T13:59:12+00:00",
      "time": "2018-07-16T14:17:42+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/e/d/83da33e735ab2b523946de9f2b0b9f2db134af/1.13-pre9.json"
    },
    {
      "assetHash": "23981354446ddc141dcf03cc4bfa6b2a9492aa90",
      "assetIndex": "1.13",
      "downloads": "4e078b2a0d4f3adc0a76343952284df03e203461",
      "downloadsId": 1,
      "hash": "38e31e164059b22e9ef549f42ef596d334d3766d",
      "lastModified": "2018-08-29T12:58:46+00:00",
      "time": "2018-07-16T14:17:42+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/3/8/e31e164059b22e9ef549f42ef596d334d3766d/1.13-pre9.json"
    }
  ],
  "next": [
    "1.13-pre10"
  ],
  "normalizedVersion": "1.13.0-pre.9",
  "previous": [
    "1.13-pre8"
  ],
  "protocol": {
    "type": "netty",
    "version": 391
  },
  "releaseTarget": "1.13",
  "releaseTime": "2018-07-16T14:17:42+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 1517
  }
}
