=== WinPlay02/mc-versions/schemas/version.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://skyrising.github.io/mc-versions/schemas/version.json",
    "$defs": {
        "version": {
            "description": "A version in the Omniarchive format",
            "type": "string",
            "pattern": "^(((server-)?([abc]|inf?-|rd-|af-)?[0-9]+[.0-9]*)|[0-9]{2}w[0-9]{2}[a-z~])a?([_-][0-9a-z]+)*$"
        },
        "semver": {
            "description": "A version number in SemVer format (see https://semver.org/ for the specification)",
            "type": "string",
            "pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
        },
        "releaseType": {
            "description": "A release type (e.g. release, snapshot, etc.)",
            "type": "string",
            "pattern": "^[a-z_]+$",
            "examples": ["release", "snapshot", "old_alpha", "old_beta"]
        },
        "sha1": {
            "description": "The SHA-1 hash of a file",
            "type": "string",
            "pattern": "^[0-9a-f]{40}$"
        },
        "downloadInfo": {
            "type": "object",
            "properties": {
                "sha1": {"$ref": "#/$defs/sha1"},
                "size": {"type": "integer", "minimum": 0},
                "url": {"type": "string", "format": "uri"}
            },
            "additionalProperties": false
        },
        "protocolVersion": {
            "type": "object",
            "properties": {
                "type": {"enum": ["classic", "modern", "netty", "netty-snapshot"]},
                "version": {"type": "integer", "minimum": 0}
            },
            "required": ["type", "version"],
            "additionalProperties": false
        },
        "worldFormat": {
            "type": "object",
            "properties": {
                "format": {"enum": ["alpha", "region", "anvil"]},
                "version": {"type": "integer"}
            },
            "required": ["format"],
            "additionalProperties": false
        },
        "manifestInfo": {
            "type": "object",
            "properties": {
                "assetHash": {"$ref": "#/$defs/sha1"},
                "assetIndex": {"type": "string"},
                "downloads": {"$ref": "#/$defs/sha1"},
                "downloadsId": {"type": "integer", "minimum": 1},
                "hash": {"$ref": "#/$defs/sha1"},
                "time": {"type": "string", "format": "date-time"},
                "type": {"$ref": "#/$defs/releaseType"},
                "url": {"type": "string", "format": "uri-reference"}
            }
        }
    },
    "type": "object",
    "properties": {
        "id": {"$ref": "#/$defs/version"},
        "client": {
            "type": "boolean",
            "description": "Whether `downloads` includes a client"
        },
        "server": {
            "type": "boolean",
            "description": "Whether `downloads` includes a server"
        },
        "sharedMappings": {
            "type": "boolean",
            "description": "Whether the obfuscation mappings for client and server are the same"
        },
        "downloads": {
            "patternProperties": {
                "^[a-z_]*$": {"$ref": "#/$defs/downloadInfo"}
            },
            "additionalProperties": false
        },
        "libraries": {
            "type": "array",
            "items": {"type": "string"}
        },
        "manifests": {
            "type": "array",
            "items": {"$ref": "#/$defs/manifestInfo"}
        },
        "normalizedVersion": {"$ref": "#/$defs/semver"},
        "previous": {"type": "array", "items": {"$ref": "#/$defs/version"}},
        "next": {"type": "array", "items": {"$ref": "#/$defs/version"}},
        "releaseTarget": {"$ref": "#/$defs/semver"},
        "releaseTime": {"type": "string", "format": "date-time"},
        "protocol": {
            "oneOf": [{
                "type": "object",
                "properties": {
                    "type": {"enum": ["classic", "modern", "netty", "netty-snapshot"]},
                    "version": {"type": "integer", "minimum": 0}
                },
                "required": ["type", "version"],
                "additionalProperties": false
            }, {
                "type": "null"
            }]
        },
        "world": {"$ref": "#/$defs/worldFormat"}
    },
    "required": ["id", "client", "server", "downloads", "normalizedVersion", "previous", "next", "releaseTarget", "releaseTime", "protocol", "world", "libraries"]
}

=== WinPlay02/mc-versions/version/13w38c.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "1424fb2795c4d86ea034b868a2fd56c6ce6912d9",
      "size": 4998459,
      "url": "https://launcher.mojang.com/v1/objects/1424fb2795c4d86ea034b868a2fd56c6ce6912d9/client.jar"
    },
    "server": {
      "sha1": "03081b4b569174ec68ef9cdd574ee4feca05dea5",
      "size": 8726163,
      "url": "https://launcher.mojang.com/v1/objects/03081b4b569174ec68ef9cdd574ee4feca05dea5/server.jar"
    },
    "windows_server": {
      "sha1": "c5cd1c39b31d3b66e7c2620769a6d6a42ebce477",
      "size": 9121939,
      "url": "https://launcher.mojang.com/v1/objects/c5cd1c39b31d3b66e7c2620769a6d6a42ebce477/windows_server.exe"
    }
  },
  "id": "13w38c",
  "libraries": [
    "com.google.code.gson:gson:2.2.2",
    "com.google.guava:guava:14.0",
    "com.ibm.icu:icu4j-core-mojang:51.2",
    "com.paulscode:codecjorbis:20101023",
    "com.paulscode:codecwav:20101023",
    "com.paulscode:libraryjavasound:20101123",
    "com.paulscode:librarylwjglopenal:20100824",
    "com.paulscode:soundsystem:20120107",
    "commons-io:commons-io:2.4",
    "java3d:vecmath:1.3.1",
    "net.java.jinput:jinput-platform:2.0.5",
    "net.java.jinput:jinput:2.0.5",
    "net.java.jutils:jutils:1.0.0",
    "net.sf.jopt-simple:jopt-simple:4.5",
    "net.sf.trove4j:trove4j:3.0.3",
    "org.apache.commons:commons-lang3:3.1",
    "org.bouncycastle:bcprov-jdk15on:1.47",
    "org.lwjgl.lwjgl:lwjgl-platform:2.9.0",
    "org.lwjgl.lwjgl:lwjgl:2.9.0",
    "org.lwjgl.lwjgl:lwjgl_util:2.9.0"
  ],
  "manifests": [
    {
      "assetHash": "770572e819335b6c0a053f8378ad88eda189fc14",
      "assetIndex": "legacy",
      "downloads": "41669d47166846b33d69b552e9906f01e2ba5da5",
      "downloadsId": 1,
      "hash": "74d1fcc1a78fee5545231656ae45c41f0b9a38f6",
      "lastModified": "2018-08-29T13:02:35+00:00",
      "time": "2013-09-20T15:11:34+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/7/4/d1fcc1a78fee5545231656ae45c41f0b9a38f6/13w38c.json"
    }
  ],
  "next": [
    "13w39a"
  ],
  "normalizedVersion": "1.7.0-alpha.13.38.c",
  "previous": [
    "13w38b"
  ],
  "protocol": {
    "type": "modern",
    "version": 79
  },
  "releaseTarget": "1.7",
  "releaseTime": "2013-09-20T15:11:34+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil"
  }
}

=== WinPlay02/mc-versions/version/1.19.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "c0898ec7c6a5a2eaa317770203a1554260699994",
      "size": 21462385,
      "url": "https://launcher.mojang.com/v1/objects/c0898ec7c6a5a2eaa317770203a1554260699994/client.jar"
    },
    "client_mappings": {
      "sha1": "150346d1c0b4acec0b4eb7f58b86e3ea1aa730f3",
      "size": 7123832,
      "url": "https://launcher.mojang.com/v1/objects/150346d1c0b4acec0b4eb7f58b86e3ea1aa730f3/client.txt"
    },
    "server": {
      "sha1": "e00c4052dac1d59a1188b2aa9d5a87113aaf1122",
      "size": 45538778,
      "url": "https://launcher.mojang.com/v1/objects/e00c4052dac1d59a1188b2aa9d5a87113aaf1122/server.jar"
    },
    "server_mappings": {
      "sha1": "1c1cea17d5cd63d68356df2ef31e724dd09f8c26",
      "size": 5552032,
      "url": "https://launcher.mojang.com/v1/objects/1c1cea17d5cd63d68356df2ef31e724dd09f8c26/server.txt"
    }
  },
  "id": "1.19",
  "libraries": [
    "com.github.oshi:oshi-core:5.8.5",
    "com.google.code.gson:gson:2.8.9",
    "com.google.guava:failureaccess:1.0.1",
    "com.google.guava:guava:31.0.1-jre",
    "com.ibm.icu:icu4j:70.1",
    "com.mojang:authlib:3.5.41",
    "com.mojang:blocklist:1.0.10",
    "com.mojang:brigadier:1.0.18",
    "com.mojang:datafixerupper:5.0.28",
    "com.mojang:javabridge:1.2.24",
    "com.mojang:logging:1.0.0",
    "com.mojang:patchy:2.2.10",
    "com.mojang:text2speech:1.13.9",
    "commons-codec:commons-codec:1.15",
    "commons-io:commons-io:2.11.0",
    "commons-logging:commons-logging:1.2",
    "io.netty:netty-buffer:4.1.77.Final",
    "io.netty:netty-codec:4.1.77.Final",
    "io.netty:netty-common:4.1.77.Final",
    "io.netty:netty-handler:4.1.77.Final",
    "io.netty:netty-resolver:4.1.77.Final",
    "io.netty:netty-transport-classes-epoll:4.1.77.Final",
    "io.netty:netty-transport-native-unix-common:4.1.77.Final",
    "io.netty:netty-transport:4.1.77.Final",
    "it.unimi.dsi:fastutil:8.5.6",
    "net.java.dev.jna:jna-platform:5.10.0",
    "net.java.dev.jna:jna:5.10.0",
    "net.sf.jopt-simple:jopt-simple:5.0.4",
    "org.apache.commons:commons-compress:1.21",
    "org.apache.commons:commons-lang3:3.12.0",
    "org.apache.httpcomponents:httpclient:4.5.13",
    "org.apache.httpcomponents:httpcore:4.4.14",
    "org.apache.logging.log4j:log4j-api:2.17.0",
    "org.apache.logging.log4j:log4j-core:2.17.0",
    "org.apache.logging.log4j:log4j-slf4j18-impl:2.17.0",
    "org.lwjgl:lwjgl-glfw:3.3.1",
    "org.lwjgl:lwjgl-jemalloc:3.3.1",
    "org.lwjgl:lwjgl-openal:3.3.1",
    "org.lwjgl:lwjgl-opengl:3.3.1",
    "org.lwjgl:lwjgl-stb:3.3.1",
    "org.lwjgl:lwjgl-tinyfd:3.3.1",
    "org.lwjgl:lwjgl:3.3.1",
    "org.slf4j:slf4j-api:1.8.0-beta4"
  ],
  "manifests": [
    {
      "assetHash": "4f4d42f50fe8ba9b5d0d4ae63993c71b46df7622",
      "assetIndex": "1.19",
      "downloads": "3afb3c3c00a8cb8a3d6e46dbab27283f66ee3e33",
      "downloadsId": 1,
      "hash": "0b5a88a99e130fd7395d8464c8a6cdfc8222ddb9",
      "lastModified": "2022-07-08T12:15:04+00:00",
      "time": "2022-06-07T09:42:18+00:00",
      "type": "release",
      "url": "https://skyrising.github.io/mc-versions/manifest/0/b/5a88a99e130fd7395d8464c8a6cdfc8222ddb9/1.19.json"
    },
    {
      "assetHash": "298a5e9205e475561c78b5ead43cb94de9ffa751",
      "assetIndex": "1.19",
      "downloads": "3afb3c3c00a8cb8a3d6e46dbab27283f66ee3e33",
      "downloadsId": 1,
      "hash": "76969a8f0751a4d62dd6c8c401d85b0d1e3d977d",
      "lastModified": "2022-07-06T14:58:47+00:00",
      "time": "2022-06-07T09:42:18+00:00",
      "type": "release",
      "url": "https://skyrising.github.io/mc-versions/manifest/7/6/969a8f0751a4d62dd6c8c401d85b0d1e3d977d/1.19.json"
    },
    {
      "assetHash": "580577f39d2b80a9498d0f54a43d5d50e1f431e2",
      "assetIndex": "1.19",
      "downloads": "3afb3c3c00a8cb8a3d6e46dbab27283f66ee3e33",
      "downloadsId": 1,
      "hash": "3cbd598a2054a217b7a55c75d76d0f704e6618ac",
      "lastModified": "2022-06-30T16:03:21+00:00",
      "time": "2022-06-07T09:42:18+00:00",
      "type": "release",
      "url": "https://skyrising.github.io/mc-versions/manifest/3/c/bd598a2054a217b7a55c75d76d0f704e6618ac/1.19.json"
    },
    {
      "assetHash": "0a4c73f7a55f2052b163739b96874a644551e9e4",
      "assetIndex": "1.19",
      "downloads": "3afb3c3c00a8cb8a3d6e46dbab27283f66ee3e33",
      "downloadsId": 1,
      "hash": "eab1b699b3b036e846d11e077c6da5375637f591",
      "lastModified": "2022-06-23T16:40:43+00:00",
      "time": "2022-06-07T09:42:18+00:00",
      "type": "release",
      "url": "https://skyrising.github.io/mc-versions/manifest/e/a/b1b699b3b036e846d11e077c6da5375637f591/1.19.json"
    },
    {
      "assetHash": "7f06db11c5a2b34d478b1de8142783654bde2aa2",
      "assetIndex": "1.19",
      "downloads": "3afb3c3c00a8cb8a3d6e46dbab27283f66ee3e33",
      "downloadsId": 1,
      "hash": "6bf2e20e61b9a95b6fa9f9225fa4d3a2fe5fceca",
      "lastModified": "2022-06-21T17:21:55+00:00",
      "time": "2022-06-07T09:42:18+00:00",
      "type": "release",
      "url": "https://skyrising.github.io/mc-versions/manifest/6/b/f2e20e61b9a95b6fa9f9225fa4d3a2fe5fceca/1.19.json"
    },
    {
      "assetHash": "d45eb5e0c20e5d753468de3d68b05c45a946f49b",
      "assetIndex": "1.19",
      "downloads": "3afb3c3c00a8cb8a3d6e46dbab27283f66ee3e33",
      "downloadsId": 1,
      "hash": "2f0e08416f8dc4c2001648d60c1d24a02d2335a7",
      "lastModified": "2022-06-15T16:29:13+00:00",
      "time": "2022-06-07T09:42:18+00:00",
      "type": "release",
      "url": "https://skyrising.github.io/mc-versions/manifest/2/f/0e08416f8dc4c2001648d60c1d24a02d2335a7/1.19.json"
    },
    {
      "assetHash": "4d2c1138477c7aafe8fb370de11ea5b23a963edc",
      "assetIndex": "1.19",
      "downloads": "3afb3c3c00a8cb8a3d6e46dbab27283f66ee3e33",
      "downloadsId": 1,
      "hash": "c0d63faac750c6fcac0d655092373133baf0b957",
      "lastModified": "2022-06-08T15:08:30+00:00",
      "time": "2022-06-07T09:42:18+00:00",
      "type": "release",
      "url": "https://skyrising.github.io/mc-versions/manifest/c/0/d63faac750c6fcac0d655092373133baf0b957/1.19.json"
    },
    {
      "assetHash": "72f061c25c8a96c4b8dd9b5609a6da6a8fb7fd73",
      "assetIndex": "1.19",
      "downloads": "3afb3c3c00a8cb8a3d6e46dbab27283f66ee3e33",
      "downloadsId": 1,
      "hash": "63b3a629bd070850a5c0821e502b6b5048fbe153",
      "lastModified": "2022-06-07T09:49:18+00:00",
      "time": "2022-06-07T09:42:18+00:00",
      "type": "release",
      "url": "https://skyrising.github.io/mc-versions/manifest/6/3/b3a629bd070850a5c0821e502b6b5048fbe153/1.19.json"
    }
  ],
  "next": [
    "22w24a"
  ],
  "normalizedVersion": "1.19.0",
  "previous": [
    "1.19-rc2"
  ],
  "protocol": {
    "type": "netty",
    "version": 759
  },
  "releaseTarget": "1.19",
  "releaseTime": "2022-06-07T09:42:18+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 3105
  }
}

=== WinPlay02/mc-versions/version/23w03a.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "dd6cb06d65063769f7581ac2f5f800fe9531e28a",
      "size": 22748586,
      "url": "https://piston-data.mojang.com/v1/objects/dd6cb06d65063769f7581ac2f5f800fe9531e28a/client.jar"
    },
    "client_mappings": {
      "sha1": "f7de4f767c3d8d9c5c4779933f175eeb738d7f65",
      "size": 7608661,
      "url": "https://piston-data.mojang.com/v1/objects/f7de4f767c3d8d9c5c4779933f175eeb738d7f65/client.txt"
    },
    "server": {
      "sha1": "b033d57035b293a9eda548db0615c1c89c21ea28",
      "size": 47187437,
      "url": "https://piston-data.mojang.com/v1/objects/b033d57035b293a9eda548db0615c1c89c21ea28/server.jar"
    },
    "server_mappings": {
      "sha1": "030aa6a26885d62a55864b16e1a2000ba91de726",
      "size": 5871550,
      "url": "https://piston-data.mojang.com/v1/objects/030aa6a26885d62a55864b16e1a2000ba91de726/server.txt"
    }
  },
  "id": "23w03a",
  "libraries": [
    "com.github.oshi:oshi-core:6.2.2",
    "com.google.code.gson:gson:2.10",
    "com.google.guava:failureaccess:1.0.1",
    "com.google.guava:guava:31.1-jre",
    "com.ibm.icu:icu4j:71.1",
    "com.mojang:authlib:3.16.29",
    "com.mojang:blocklist:1.0.10",
    "com.mojang:brigadier:1.0.18",
    "com.mojang:datafixerupper:5.0.28",
    "com.mojang:logging:1.1.1",
    "com.mojang:patchy:2.2.10",
    "com.mojang:text2speech:1.13.9",
    "commons-codec:commons-codec:1.15",
    "commons-io:commons-io:2.11.0",
    "commons-logging:commons-logging:1.2",
    "io.netty:netty-buffer:4.1.82.Final",
    "io.netty:netty-codec:4.1.82.Final",
    "io.netty:netty-common:4.1.82.Final",
    "io.netty:netty-handler:4.1.82.Final",
    "io.netty:netty-resolver:4.1.82.Final",
    "io.netty:netty-transport-classes-epoll:4.1.82.Final",
    "io.netty:netty-transport-native-unix-common:4.1.82.Final",
    "io.netty:netty-transport:4.1.82.Final",
    "it.unimi.dsi:fastutil:8.5.9",
    "net.java.dev.jna:jna-platform:5.12.1",
    "net.java.dev.jna:jna:5.12.1",
    "net.sf.jopt-simple:jopt-simple:5.0.4",
    "org.apache.commons:commons-compress:1.21",
    "org.apache.commons:commons-lang3:3.12.0",
    "org.apache.httpcomponents:httpclient:4.5.13",
    "org.apache.httpcomponents:httpcore:4.4.15",
    "org.apache.logging.log4j:log4j-api:2.19.0",
    "org.apache.logging.log4j:log4j-core:2.19.0",
    "org.apache.logging.log4j:log4j-slf4j2-impl:2.19.0",
    "org.joml:joml:1.10.5",
    "org.lwjgl:lwjgl-glfw:3.3.1",
    "org.lwjgl:lwjgl-jemalloc:3.3.1",
    "org.lwjgl:lwjgl-openal:3.3.1",
    "org.lwjgl:lwjgl-opengl:3.3.1",
    "org.lwjgl:lwjgl-stb:3.3.1",
    "org.lwjgl:lwjgl-tinyfd:3.3.1",
    "org.lwjgl:lwjgl:3.3.1",
    "org.slf4j:slf4j-api:2.0.1"
  ],
  "manifests": [
    {
      "assetHash": "b5d533e30f493be215e805f1affb572b73a27dad",
      "assetIndex": "2",
      "downloads": "76c3f0c654694273fd3cf17578153f36a36ae9e8",
      "downloadsId": 1,
      "hash": "732c29bf85113da17ea4b9aa9c0535f5c8fa6ad7",
      "lastModified": "2023-02-01T14:36:18+00:00",
      "time": "2023-01-18T13:10:31+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/7/3/2c29bf85113da17ea4b9aa9c0535f5c8fa6ad7/23w03a.json"
    },
    {
      "assetHash": "63b14365d7df8a206d2fae60e3400d84bab5a7a4",
      "assetIndex": "2",
      "downloads": "76c3f0c654694273fd3cf17578153f36a36ae9e8",
      "downloadsId": 1,
      "hash": "3f1db363e2e6c5dc41d6a9de9e3ae51e38f0d788",
      "lastModified": "2023-01-24T15:38:24+00:00",
      "time": "2023-01-18T13:10:31+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/3/f/1db363e2e6c5dc41d6a9de9e3ae51e38f0d788/23w03a.json"
    },
    {
      "assetHash": "f465df3c585b67233e863479efd6b7dbf86aa68e",
      "assetIndex": "2",
      "downloads": "76c3f0c654694273fd3cf17578153f36a36ae9e8",
      "downloadsId": 1,
      "hash": "f16a69f6e465420c8ce6941774c62ed6b651a79a",
      "lastModified": "2023-01-18T13:30:24+00:00",
      "time": "2023-01-18T13:10:31+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/f/1/6a69f6e465420c8ce6941774c62ed6b651a79a/23w03a.json"
    }
  ],
  "next": [
    "23w04a"
  ],
  "normalizedVersion": "1.19.4-alpha.23.3.a",
  "previous": [
    "1.19.3"
  ],
  "protocol": {
    "type": "netty-snapshot",
    "version": 115
  },
  "releaseTarget": "1.19.4",
  "releaseTime": "2023-01-18T13:10:31+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 3320
  }
}

=== WinPlay02/mc-versions/version/1.7.6-pre2.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "24e28d53aecff54ff9be2a1ba1ffe008b86f7ed6",
      "size": 5338685,
      "url": "https://launcher.mojang.com/v1/objects/24e28d53aecff54ff9be2a1ba1ffe008b86f7ed6/client.jar"
    },
    "server": {
      "sha1": "5aa5deddbe750a384bdb5ed0652bbda33cf4e5c8",
      "size": 9480864,
      "url": "https://launcher.mojang.com/v1/objects/5aa5deddbe750a384bdb5ed0652bbda33cf4e5c8/server.jar"
    },
    "windows_server": {
      "sha1": "f2e07d3d06e4daba5d107f5d1e59324ee25e4679",
      "size": 9875104,
      "url": "https://launcher.mojang.com/v1/objects/f2e07d3d06e4daba5d107f5d1e59324ee25e4679/windows_server.exe"
    }
  },
  "id": "1.7.6-pre2",
  "libraries": [
    "com.google.code.gson:gson:2.2.4",
    "com.google.guava:guava:15.0",
    "com.ibm.icu:icu4j-core-mojang:51.2",
    "com.mojang:authlib:1.5.5",
    "com.mojang:netty:1.8.8",
    "com.paulscode:codecjorbis:20101023",
    "com.paulscode:codecwav:20101023",
    "com.paulscode:libraryjavasound:20101123",
    "com.paulscode:librarylwjglopenal:20100824",
    "com.paulscode:soundsystem:20120107",
    "commons-codec:commons-codec:1.9",
    "commons-io:commons-io:2.4",
    "io.netty:netty-all:4.0.10.Final",
    "java3d:vecmath:1.3.1",
    "net.java.jinput:jinput-platform:2.0.5",
    "net.java.jinput:jinput:2.0.5",
    "net.java.jutils:jutils:1.0.0",
    "net.sf.jopt-simple:jopt-simple:4.5",
    "net.sf.trove4j:trove4j:3.0.3",
    "org.apache.commons:commons-lang3:3.1",
    "org.apache.logging.log4j:log4j-api:2.0-beta9",
    "org.apache.logging.log4j:log4j-core:2.0-beta9",
    "org.lwjgl.lwjgl:lwjgl-platform:2.9.1",
    "org.lwjgl.lwjgl:lwjgl:2.9.1",
    "org.lwjgl.lwjgl:lwjgl_util:2.9.1",
    "tv.twitch:twitch-platform:5.16",
    "tv.twitch:twitch:5.16"
  ],
  "manifests": [
    {
      "assetHash": "545510a60f526b9aa8a38f9c0bc7a74235d21675",
      "assetIndex": "1.7.4",
      "downloads": "4cbd6976a6b67a16ebc8e3ee388b7ce3836fce01",
      "downloadsId": 1,
      "hash": "ba4dcff2b09e8b070d43a213d6abc87bde19437a",
      "lastModified": "2021-12-15T16:01:01+00:00",
      "time": "2014-03-08T11:00:01+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/b/a/4dcff2b09e8b070d43a213d6abc87bde19437a/1.7.6-pre2.json"
    },
    {
      "assetHash": "545510a60f526b9aa8a38f9c0bc7a74235d21675",
      "assetIndex": "1.7.4",
      "downloads": "4cbd6976a6b67a16ebc8e3ee388b7ce3836fce01",
      "downloadsId": 1,
      "hash": "09aeca43c0582659a38143ca9b55616a8a2d8b58",
      "lastModified": "2021-07-07T14:04:15+00:00",
      "time": "2014-03-08T11:00:01+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/0/9/aeca43c0582659a38143ca9b55616a8a2d8b58/1.7.6-pre2.json"
    },
    {
      "assetHash": "545510a60f526b9aa8a38f9c0bc7a74235d21675",
      "assetIndex": "1.7.4",
      "downloads": "4cbd6976a6b67a16ebc8e3ee388b7ce3836fce01",
      "downloadsId": 1,
      "hash": "3de9556107748d7acca8b52874f65a9286787f45",
      "lastModified": "2018-08-29T13:02:11+00:00",
      "time": "2014-03-08T11:00:01+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/3/d/e9556107748d7acca8b52874f65a9286787f45/1.7.6-pre2.json"
    }
  ],
  "next": [
    "1.7.6"
  ],
  "normalizedVersion": "1.7.6-pre.2",
  "previous": [
    "1.7.6-pre1"
  ],
  "protocol": {
    "type": "netty",
    "version": 5
  },
  "releaseTarget": "1.7.6",
  "releaseTime": "2014-04-04T00:00:00+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil"
  }
}

=== WinPlay02/mc-versions/version/1.19.4-pre1.json
{
  "$schema": "https://skyrising.github.io/mc-versions/schemas/version.json",
  "client": true,
  "downloads": {
    "client": {
      "sha1": "1da03ea094c11b77e6784e6a816b73f5f5dc57b7",
      "size": 23465141,
      "url": "https://piston-data.mojang.com/v1/objects/1da03ea094c11b77e6784e6a816b73f5f5dc57b7/client.jar"
    },
    "client_mappings": {
      "sha1": "4e844a179888db439959bef2101ff8b5dc23c676",
      "size": 7837141,
      "url": "https://piston-data.mojang.com/v1/objects/4e844a179888db439959bef2101ff8b5dc23c676/client.txt"
    },
    "server": {
      "sha1": "0bc471b96bb0edbc2f03e6cdc3ad981f7a4f5f8a",
      "size": 47514454,
      "url": "https://piston-data.mojang.com/v1/objects/0bc471b96bb0edbc2f03e6cdc3ad981f7a4f5f8a/server.jar"
    },
    "server_mappings": {
      "sha1": "33bc57d4a1cef5540a1673b2bc0526240227355f",
      "size": 6039716,
      "url": "https://piston-data.mojang.com/v1/objects/33bc57d4a1cef5540a1673b2bc0526240227355f/server.txt"
    }
  },
  "id": "1.19.4-pre1",
  "libraries": [
    "com.github.oshi:oshi-core:6.2.2",
    "com.google.code.gson:gson:2.10",
    "com.google.guava:failureaccess:1.0.1",
    "com.google.guava:guava:31.1-jre",
    "com.ibm.icu:icu4j:71.1",
    "com.mojang:authlib:3.17.30",
    "com.mojang:blocklist:1.0.10",
    "com.mojang:brigadier:1.0.18",
    "com.mojang:datafixerupper:6.0.6",
    "com.mojang:logging:1.1.1",
    "com.mojang:patchy:2.2.10",
    "com.mojang:text2speech:1.13.9",
    "commons-codec:commons-codec:1.15",
    "commons-io:commons-io:2.11.0",
    "commons-logging:commons-logging:1.2",
    "io.netty:netty-buffer:4.1.82.Final",
    "io.netty:netty-codec:4.1.82.Final",
    "io.netty:netty-common:4.1.82.Final",
    "io.netty:netty-handler:4.1.82.Final",
    "io.netty:netty-resolver:4.1.82.Final",
    "io.netty:netty-transport-classes-epoll:4.1.82.Final",
    "io.netty:netty-transport-native-unix-common:4.1.82.Final",
    "io.netty:netty-transport:4.1.82.Final",
    "it.unimi.dsi:fastutil:8.5.9",
    "net.java.dev.jna:jna-platform:5.12.1",
    "net.java.dev.jna:jna:5.12.1",
    "net.sf.jopt-simple:jopt-simple:5.0.4",
    "org.apache.commons:commons-compress:1.21",
    "org.apache.commons:commons-lang3:3.12.0",
    "org.apache.httpcomponents:httpclient:4.5.13",
    "org.apache.httpcomponents:httpcore:4.4.15",
    "org.apache.logging.log4j:log4j-api:2.19.0",
    "org.apache.logging.log4j:log4j-core:2.19.0",
    "org.apache.logging.log4j:log4j-slf4j2-impl:2.19.0",
    "org.joml:joml:1.10.5",
    "org.lwjgl:lwjgl-glfw:3.3.1",
    "org.lwjgl:lwjgl-jemalloc:3.3.1",
    "org.lwjgl:lwjgl-openal:3.3.1",
    "org.lwjgl:lwjgl-opengl:3.3.1",
    "org.lwjgl:lwjgl-stb:3.3.1",
    "org.lwjgl:lwjgl-tinyfd:3.3.1",
    "org.lwjgl:lwjgl:3.3.1",
    "org.slf4j:slf4j-api:2.0.1"
  ],
  "manifests": [
    {
      "assetHash": "4242d79a4a9cad75fa0cfcd94eac3fd311a88f27",
      "assetIndex": "3",
      "downloads": "7ba9651ad033f578ddd33ebbd74662b18c1412ac",
      "downloadsId": 1,
      "hash": "00d34b23f252b517dbb766bc2f041aad526c9fb0",
      "lastModified": "2023-02-22T16:12:55+00:00",
      "time": "2023-02-22T16:00:34+00:00",
      "type": "snapshot",
      "url": "https://skyrising.github.io/mc-versions/manifest/0/0/d34b23f252b517dbb766bc2f041aad526c9fb0/1.19.4-pre1.json"
    }
  ],
  "next": [],
  "normalizedVersion": "1.19.4-pre.1",
  "previous": [
    "23w07a"
  ],
  "protocol": {
    "type": "netty-snapshot",
    "version": 120
  },
  "releaseTarget": "1.19.4",
  "releaseTime": "2023-02-22T16:00:34+00:00",
  "server": true,
  "sharedMappings": true,
  "world": {
    "format": "anvil",
    "version": 3330
  }
}
